Adding duckduckgo email as a user
haraka/haraka.github.io pull request #36
Opened 2023-03-17 00:34 UTC by rohitsud

Mail headers show this project in use

`Received: from smtp3-1.bur.wordpress.com (smtp3-1.bur.wordpress.com [192.0.123.40]) by smtp-inbound1.duck.com (Haraka/2.8.28) with ESMTPS id 7976BCBB-226C-4C1B-943E-183CC0D2B5D3.1 envelope-from <***@b.wordpress.com> tls TLS_AES_256_GCM_SHA384; Thu, 16 Mar 2023 20:29:10 -0400`

2023-03-24 13:14 UTC, sent requested changes

2023-03-24 13:14 UTC, sent commented on content/5.users.md
> +* <a href="https://duckduckgo.com/email/"DuckDuckGo Email Protection</a>
```suggestion
* <a href="https://duckduckgo.com/email/">DuckDuckGo Email Protection</a>
```

2023-03-26 12:47 UTC, divine commented
Hello @msimerson,

Can we merge this, please?

Thanks!

2023-03-26 12:48 UTC, sent commented
Hello @msimerson,

Can we merge this, please?

Thanks!

2023-03-26 18:59 UTC, merged